#This is the file which will have the questions of Python with answers
#The format is simple, we will have a list, and then inside a list we will have another list
#In the list inside the main list will be the questions and answers
#And we will use indexing, 0 of the list will be a question, 1 will be the answer

questions=[
    ["What is Python?","Python is a high level programming language popular for its simplicity."],
    ["What is a String?","String is the built-in text sequence data type used to represent textual data"],
    ["What will be the answer of: \"10\"*2","Answer: \"1010\""],
    ["How many data types do Python has?","There are 7 major"],
    ["What do str means?","str is how the string data type is represented in code in Python."],
    ["What do .lower() method of str do?","It changes all the alphabets and letters of a string in lower case. If the letter is in uppercase, it will turn to lower and the lower will remain lower."],
    ["Are string mutable?","No, string are unmutable."],
    ["What will be the output of\n\"12\"+2","An error, str can only + with str only."],
    ["What will be the output of this:\nt=\"Hello\"\nt.upper()\nprint(t)","Hello"],
    ["Find the syntax error:\nst.1=0","The . in st.1 causes the error. A variable can't have symbols except underscore _ "],
    ["What will be the output:\nprint(True+True)","2"],
    ["What will be the output:\nbool(\"False\")","True"],
    ["Which is the special data type?","None from NoneType"],
    ["What will be the output:\nprint(bool(\"\"))","False"],
    ["What will be the output:\nprint(bool([\"\"]))","True"],
    ["Is this right:\nprint({1,2,3,4,2,2,8})\nOutput:\n{1,2,3,4,2,2,8}","No, set can never contain duplicates."],
    ["What will be the output:\nif []:\n\tprint(\"Yes\")\nelse:\n\tprint(\"No\")","No"],
    ["Is this right:\ndef func(a=0,b):\n","No, it will be an syntax error. If a parameter is made default then all the parameters after it must be default as well."],
    ["Will this program work:\ntry:\n\tprint(\"Yes!\")","No, if try is being used then except must be added to the program next to it."],
    ["What will be:\nprint(\"2\">\"10\")","True"],
    ["What will be:\n\"1\"+\"1\"","11"],
    ["What will be:\n\"5\"*4","5555"],
    ["What will be:\n10+1","11"],
    ["What will be:\n4/0","It will cause: ZeroDivisionError"],
    ["What will be:\n0/1","0.0"],
    ["What will be:\n10*4/2","20"],
    ["What will be:\n2**3","8"],
    ["What do \\n escape sequance do?","Makes a new line in a string"],
    ["Which error will happen:\ndef num(n:int):\n\tprint(n)\nnum(\"hi\")","No error :3\n(seriously, I was shocked when I tested it lol)"],
    ["True or False:\n\"2\">\"10\"","True"],
    ["True or False:\n20!=20","False"],
    ["True or False:\n2==(4-2+4-3+1)","False"],
    ["True or False:\nbool(0)","False"],
    ["True or False:\nbool(False)","False"],
    ["True or False:\nbool(\"False\")","True"],
    ["True or False:\nbool(set())","False"],
    ["True or False:\nbool(12)","True"],
    ["True or False:\nbool(100-99+1-2==False)","True"],
    ["True or False:\nbool(a=0)","Error lol\nTypeError, bool takes no keyword arguement"],
    ["True or False:\ndef num(n:int):\n\tpass\nbool(num(120))","False lol\nI don't know how, haha, it's funny"],
    ["True or False:\ndef num(n:int):\n\tpass\nbool(num)","True\nDon't ask me how, google it :3, but I believe, when we haven't given the arguments or bracket, it will be True, if we give, then it will first run the function and then False"]
]
