#This is the file which will have the questions of Python with answers
#The format is simple, we will have a list, and then inside a list we will have another list
#In the list inside the main list will be the questions and answers
#And we will use indexing, 0 of the list will be a question, 1 will be the answer

questions=[
    ["What is Python?","Python is a high level programming language popular for its simplicity."],
    ["What is a String?","String is the built-in text sequence data type used to represent textual data"],
    ["What will be the answer of: \"10\"*2","Answer: \"1010\""],
    ["How many data types do Python has?","There are 7 major"],
    ["What do str means?","str is how the string data type is represented in code in Python."],
    ["What do .lower() method of str do?","It changes all the alphabets and letters of a string in lower case. If the letter is in uppercase, it will turn to lower and the lower will remain lower."],
    ["Are string mutable?","No, string are unmutable."],
    ["What will be the output of\n\"12\"+2","An error, str can only + with str only."],
    ["What will be the output of this:\nt=\"Hello\"\nt.upper()\nprint(t)","Hello"],
    ["Find the syntax error:\nst.1=0","The . in st.1 causes the error. A variable can't have symbols except underscore _ "],
    ["What will be the output:\nprint(True+True)","2"],
    ["What will be the output:\nbool(\"False\")","True"],
    ["Which is the special data type?","None from NoneType"],
    ["What will be the output:\nprint(bool(\"\"))","False"],
    ["What will be the output:\nprint(bool([\"\"]))","True"],
    ["Is this right:\nprint({1,2,3,4,2,2,8})\nOutput:\n{1,2,3,4,2,2,8}","No, set can never contain duplicates."],
    ["What will be the output:\nif []:\n\tprint(\"Yes\")\nelse:\n\tprint(\"No\")","No"],
    ["Is this right:\ndef func(a=0,b):\n","No, it will be an syntax error. If a parameter is made default then all the parameters after it must be default as well."],
    ["Will this program work:\ntry:\n\tprint(\"Yes!\")","No, if try is being used then except must be added to the program next to it."],
    ["What will be:\nprint(\"2\">\"10\")","True"],
    ["What will be:\n\"1\"+\"1\"","11"],
    ["What will be:\n\"5\"*4","5555"],
    ["What will be:\n10+1","11"],
    ["What will be:\n4/0","It will cause: ZeroDivisionError"],
    ["What will be:\n0/1","0.0"],
    ["What will be:\n10*4/2","20"],
    ["What will be:\n2**3","8"],
    ["What do \\n escape sequance do?","Makes a new line in a string"],
    ["Which error will happen:\ndef num(n:int):\n\tprint(n)\nnum(\"hi\")","No error :3\n(seriously, I was shocked when I tested it lol)"],
    ["True or False:\n\"2\">\"10\"","True"],
    ["True or False:\n20!=20","False"],
    ["True or False:\n2==(4-2+4-3+1)","False"],
    ["True or False:\nbool(0)","False"],
    ["True or False:\nbool(False)","False"],
    ["True or False:\nbool(\"False\")","True"],
    ["True or False:\nbool(set())","False"],
    ["True or False:\nbool(12)","True"],
    ["True or False:\nbool(100-99+1-2==False)","True"],
    ["True or False:\nbool(a=0)","Error lol\nTypeError, bool takes no keyword arguement"],
    ["True or False:\ndef num(n:int):\n\tpass\nbool(num(120))","False lol\nI don't know how, haha, it's funny"],
    ["True or False:\ndef num(n:int):\n\tpass\nbool(num)","True\nDon't ask me how, google it :3, but I believe, when we haven't given the arguments or bracket, it will be True, if we give, then it will first run and then False"],
    ["Find the error:\nfor i in range(100)\n\tprint(i)","The \":\" is missing after range"],
    ["Find the error:\na=5\nb=10\nprint(100/(a-b+5))","ZeroDivisionError\na-b+5=0, and 0 is the divisor"],
    ["Find the error:\nc=0\nif a==0:\n\tprint(\"Yes!\")","There's no keyword or variable like a present in the code"],
    ["Find the error:\nbol(0)","Spelling of bool"],
    ["Find the error:\n\"\"\"Hello World!\"\"","That one \" is missing at the end"],
    ["Find the error:\ny=\"hello\"\ny=int(y)","You can't transform a string of aphabets and symbols an integer"],
    ["Find the error:\npirnt(\"Hello world!\")","Spelling of print"],
    ["Find the error:\nprint(\"Hello\")\nprint(1)\nprint(0)","No error lol"],
    ["Find the error:\nif 1:\n\tprint(1)\nelse:\n\tprint(0)","No error lol"],
    ["Find the error:\ntry:\n\tprint(\"Yes\")\n\texcept:\n\t\tprint(\"No\")","Indentation error, except should at the position where try is"],
    ["What will be the output:\nprint(\"Hello World!\")","Hellow World"],
    ["What will be the output:\nfor i in range(1,3):\n\tprint(\"*\"*i,end=\"-\")","*-**-"],
    ["What will be the output:\nprint(0==True)","False"],
    ["What will be the output:\nprint(1==True)","True"],
    ["What will be the output:\nprint(12==True)","False"],
    ["What will be the output:\nprint(bool(\"\")==False)","True"],
    ["What will be the output:\nprint(True)","True"],
    ["What will be the output:\nprint(12==False)","True"],
    ["What will be the output:\nprint(1001!=True)","True"],
    ["What will be the output:\nprint(001==False)","SyntaxError\nAn integer shouldn't start with 0, unless it is a decimal like 0.1, which is float."],
    ["l=[1,2,3,4]\nprint(l.pop())","4"],
    ["l=[1,2,3]\nl.pop()\nprint(l)","[1,2]"],
    ["l=[]\nprint(l.append(10))","None"],
    ["l=[]\nl.append(10)\nprint(l)","[10]"],
    ["s={1,2,3,4,4,44}\nprint(s)","{1,2,3,4,44}"],
    ["d={\"number\":1,\"number2\":2}\nprint(d[\"number\"])","1"],
    ["d={}\nd[\"hello\"]=1\nprint(d)","{\"hello\":1}"],
    ["Write the code to print 'HelloWorld!' in the terminal","print(\"HelloWorld!\")"],
    ["Write a code of for loop to print numbers 0 to 9","*An example:*\nfor i in range(10):\n\tprint(i)"],
    ["Write a code of while loop to print numbers 0 to 9","*An example:*\ni=0\nwhile i<10:\n\tprint(i)\n\ti+=1"],
    ["Change the value of the variable's value\nw=\"Hello\"\nTo \"hello\" by str method","w=w.lower()"],
    ["Change the variable\na=10\nTo a string","Example:\na=10\na=str(a)"],
    ["Write a code find the the characters of the string\n\"Hello World!\"","a=\"Hello World!\"\nprint(len(a))"],
    ["Write a code to get a random number from 0 to 10","Example:\nprint(random.randint(0,10))"],
    ["Swap the variables:\na=5\nb=10","Example:\na,b=b,a"],
    ["Make a variable y having 10, x having 9 and add them and show on the terminal","Example:\ny=10\nx=9\nprint(y+x)"],
    ["Ask from the user for his/her/their name and print it","name=input(\"Name: \")\nprint(name)"],
    ["How to write a single line comment?","#use the hashtag for the single line comment"],
    ["How to write a multi line comment?","\"\"\"Use triple quotation mark, and make sure it's not in a variable\"\"\""],
    ["Ask for age and if the age is above 14, say Hi, otherwise Hello","Example:\nage=int(input(\"Age: \"))\nif age>14:\n\tprint(\"Hi\")\nelse:\n\tprint(\"Hello\")"],
    ["Write a code to find whether \"a\" is in the string or not","word=input()\nif \"a\" in word:\n\tprint(\"There is \"a\"!\")\nelse:\n\tprint(\"No\")"],
    ["Take a name and say Hi to him/her/them","name=input(\"Name: \")\nprint(\"Hi \"+name)"],
    ["Calculate 124*23/52+2-7*44/12 and show the answer in the terminal","print(124*23/52+2-7*44/12)\n\nAnswer:31.17948717948718"],
]
